=== borisblack/scicms-core/src/main/resources/schema/model.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "model.schema.json",
  "title": "Model",
  "description": "Schema Model",
  "type": "object",
  "properties": {
    "coreVersion": {
      "description": "Core version",
      "type": "string",
      "enum": ["v1"]
    },
    "kind": {
      "description": "Model kind",
      "type": "string",
      "enum": ["Item", "ItemTemplate"]
    },
    "includeTemplates": {
      "description": "Included templates",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "metadata": {
      "description": "Model metadata",
      "$ref": "#/definitions/Metadata"
    },
    "spec": {
      "description": "Item specification",
      "type": "object",
      "properties": {
        "attributes": {
          "description": "Item attributes",
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {
            "$ref": "#/definitions/Attribute"
          }
        },
        "indexes": {
          "description": "Item indexes. If the index name begins with _, it will be prefixed by the table name",
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {
            "$ref": "#/definitions/Index"
          }
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false,
  "required": ["coreVersion", "kind", "metadata", "spec"],
  "definitions": {
    "Metadata": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Item name starting with a lowercase character (required)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "displayName": {
          "description": "Display name (optional, name is used by default)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "pluralName": {
          "description": "Plural name (required)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "displayPluralName": {
          "description": "Display plural name (optional, pluralName is used by default)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "titleAttribute": {
          "description": "Title attribute name (optional, 'id' is used by default)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "dataSource": {
          "description": "Data source name (required)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "tableName": {
          "description": "Table name (optional, pluralName in lowercase with whitespaces replaced by _ is used by default). Prefixes core_ and sec_ are not allowed",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "description": {
          "description": "Description (optional, null by default)",
          "type": "string",
          "minLength": 1,
          "maxLength": 250
        },
        "icon": {
          "description": "Icon name (optional, null by default)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "core": {
          "description": "Core flag (optional, false by default)",
          "type": "boolean"
        },
        "performDdl": {
          "description": "DDL operation performing flag (optional, false by default)",
          "type": "boolean"
        },
        "versioned": {
          "description": "Versioning flag (optional, false by default)",
          "type": "boolean"
        },
        "manualVersioning": {
          "description": "Manual versioning flag (optional, false by default)",
          "type": "boolean"
        },
        "localized": {
          "description": "Localization flag (optional, false by default)",
          "type": "boolean"
        },
        "revisionPolicy": {
          "description": "Revision policy ID (optional, null by default)",
          "type": "string"
        },
        "lifecycle": {
          "description": "Lifecycle ID (optional, null by default)",
          "type": "string"
        },
        "permission": {
          "description": "Permission ID (optional, Default Access ID by default)",
          "type": "string"
        },
        "notLockable": {
          "description": "Disabling lock/unlock flag (optional, false by default)",
          "type": "boolean"
        },
        "implementation": {
          "description": "Implementation class (optional, null by default)",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": ["name"]
    },
    "Attribute": {
      "type": "object",
      "properties": {
        "type": {
          "description": "Attribute type (required)",
          "type": "string",
          "enum": [
            "uuid", "string", "text", "enum", "sequence", "email", "password", "int", "long", "float", "double",
            "decimal", "date", "time", "datetime", "timestamp", "bool", "array", "json", "media", "relation"
          ]
        },
        "columnName": {
          "description": "Column name (optional, lowercase attribute name is used in database by default). Can be null for oneToMany and manyToMany relations",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "displayName": {
          "description": "Display name (optional, null by default)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "description": {
          "description": "Description (optional, null by default)",
          "type": "string",
          "minLength": 1,
          "maxLength": 250
        },
        "seqName": {
          "description": "Sequence name (required for sequence type)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "enumSet": {
          "description": "Enumeration entries (required for enum type)",
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 50
          },
          "minItems": 1
        },
        "relType": {
          "description": "Relation type (required for relation type)",
          "type": "string",
          "enum": ["oneToOne", "manyToOne", "oneToMany", "manyToMany"]
        },
        "target": {
          "description": "Target item name (required for relation type)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "intermediate": {
          "description": "Intermediate item name (required for manyToMany relation type). Intermediate item includes source and target attributes",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "mappedBy": {
          "description": "In bidirectional relations, the owning side declares the inversedBy key while the inversed side declares the mappedBy key",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "inversedBy": {
          "description": "In bidirectional relations, the owning side declares the inversedBy key while the inversed side declares the mappedBy key",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "keyed": {
          "description": "Primary key flag (used only for id attribute)",
          "type": "boolean"
        },
        "required": {
          "description": "Mandatory flag (optional, false by default)",
          "type": "boolean"
        },
        "defaultValue": {
          "description": "Default value (optional, null by default)",
          "type": ["string", "number", "boolean"],
          "minLength": 1,
          "maxLength": 50
        },
        "unique": {
          "description": "Uniqueness flag (optional, false by default). Additional columns may be added to the unique index depending on configuration parameters (versioning.include-in-unique-index and i18n.include-in-unique-index) and attributes (versioned and localized). If other logic is needed, use the indexes section",
          "type": "boolean"
        },
        "indexed": {
          "description": "Uniqueness flag (optional, false by default). For versioned or localized item non-unique index can be added on par with a composite unique index",
          "type": "boolean"
        },
        "private": {
          "description": "Privacy flag",
          "type": "boolean"
        },
        "pattern": {
          "description": "Regex pattern (optional, null by default). For string type",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "length": {
          "description": "String length (optional, null by default). For string type",
          "type": "integer",
          "minimum": 1
        },
        "precision": {
          "description": "Precision (optional, null by default). For decimal type",
          "type": "integer",
          "minimum": 0
        },
        "scale": {
          "description": "Scale (optional, null by default). For decimal type",
          "type": "integer",
          "minimum": 0
        },
        "minRange": {
          "description": "Minimum range (optional, null by default). For int, long, float, double and decimal types",
          "type": "number"
        },
        "maxRange": {
          "description": "Maximum range (optional, null by default). For int, long, float, double and decimal types",
          "type": "number"
        },
        "colHidden": {
          "description": "Hide column in UI table (optional, null by default)",
          "type": "boolean"
        },
        "colWidth": {
          "description": "Column width in UI table (optional, null by default)",
          "type": "number"
        },
        "fieldHidden": {
          "description": "Hide field in UI form (optional, null by default)",
          "type": "boolean"
        },
        "fieldWidth": {
          "description": "Field width in UI form (optional, null by default)",
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": ["type"]
    },
    "Index": {
      "type": "object",
      "properties": {
        "columns": {
          "description": "Index columns. The index will be created with the specified columns only (without additional version or locale columns)",
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 50
          },
          "minItems": 1
        },
        "unique": {
          "description": "Uniqueness flag (optional, false by default)",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "required": ["columns"]
    }
  }
}

=== borisblack/scicms-core/src/main/resources/schema/custom/example-item.json
{
  "coreVersion": "v1",
  "kind": "Item",
  "includeTemplates": [
    "defaultItemTemplate"
  ],
  "metadata": {
    "name": "example",
    "displayName": "Example",
    "pluralName": "examples",
    "displayPluralName": "Examples",
    "dataSource": "main",
    "tableName": "examples",
    "titleAttribute": "name",
    "description": "Examples",
    "icon": "TagOutlined",
    "core": false,
    "performDdl": false,
    "versioned": false,
    "manualVersioning": false,
    "localized": false,
    "notLockable": false
  },
  "spec": {
    "attributes": {
      "name": {
        "type": "string",
        "columnName": "name",
        "displayName": "Name",
        "description": "Name",
        "required": true,
        "unique": true,
        "indexed": false,
        "private": false,
        "length": 50
      },
      "displayName": {
        "type": "string",
        "columnName": "display_name",
        "displayName": "Display Name",
        "description": "Display Name",
        "length": 50
      },
      "description": {
        "type": "string",
        "columnName": "description",
        "displayName": "Description",
        "description": "Description",
        "length": 250
      },
      "product": {
        "type": "relation",
        "relType": "manyToOne",
        "target": "product",
        "inversedBy": "parts",
        "columnName": "product_id",
        "displayName": "Product",
        "description": "Product"
      },
      "partType": {
        "type": "enum",
        "columnName": "part_type",
        "enumSet": [
          "Assembly",
          "Part"
        ],
        "displayName": "Part Type",
        "description": "Part Type"
      },
      "ownershipType": {
        "type": "enum",
        "columnName": "ownership_type",
        "enumSet": [
          "Manufactured",
          "Borrowed",
          "Bought"
        ],
        "displayName": "Ownership Type",
        "description": "Ownership Type"
      },
      "units": {
        "type": "enum",
        "columnName": "units",
        "enumSet": [
          "pcs",
          "kg"
        ],
        "displayName": "Units",
        "description": "Units"
      },
      "cost": {
        "type": "decimal",
        "columnName": "cost",
        "displayName": "Cost",
        "description": "Cost",
        "precision": 14,
        "scale": 4,
        "minRange": 0
      },
      "weight": {
        "type": "decimal",
        "columnName": "weight",
        "displayName": "Weight",
        "description": "Weight",
        "precision": 14,
        "scale": 4,
        "minRange": 0
      },
      "releaseDate": {
        "type": "datetime",
        "columnName": "release_date",
        "displayName": "Release Date",
        "description": "Release Date"
      },
      "effectiveDate": {
        "type": "datetime",
        "columnName": "effective_date",
        "displayName": "Effective Date",
        "description": "Effective Date"
      },
      "supersededDate": {
        "type": "datetime",
        "columnName": "superseded_date",
        "displayName": "Superseded Date",
        "description": "Superseded Date"
      },
      "startSheet": {
        "type": "relation",
        "relType": "manyToOne",
        "target": "startSheet",
        "inversedBy": "parts",
        "columnName": "start_sheet_id",
        "displayName": "Start Sheet",
        "description": "Start Sheet"
      }
    },
    "indexes": {
      "examples_name_uk": {
        "columns": [
          "name"
        ],
        "unique": true
      }
    }
  }
}
